### ISSUE TITLE
Craft superapple error (maybe ruby blocks spell error)

### ISSUE THREAD

**Issue by shenyx110** [skniro/Agree-Super_Apple#6]
### Mod Version

3.2.8-1.21.1-NeoForge

### error description

It is suspected that the misspelling of the word (block and blocks) is the result of a error tag 
![截屏2024-09-25 02 26 16](https://github.com/user-attachments/assets/89e86e7b-df3b-4e46-8edc-d96522ddca6e)
![截屏2024-09-25 02 28 47](https://github.com/user-attachments/assets/e1b79103-d512-4f0a-9f3c-fa1d293f70b2)
![截屏2024-09-25 02 28 54](https://github.com/user-attachments/assets/fa09b20a-9331-459c-b7fd-fe7dfffafab3)
[minecraft-exported-crash-info-2024-09-25T02-30-35.zip](https://github.com/user-attachments/files/17119342/minecraft-exported-crash-info-2024-09-25T02-30-35.zip)
[minecraft-exported-logs-2024-09-25T02-30-00.log](https://github.com/user-attachments/files/17119346/minecraft-exported-logs-2024-09-25T02-30-00.log)
[minecraft-exported-logs-2024-09-25T02-30-39.log](https://github.com/user-attachments/files/17119347/minecraft-exported-logs-2024-09-25T02-30-39.log)

**Comment by skniro** [comment]
Try 1.21.1-3.2.12
